### ISSUE TITLE
the config file of the teacher model

### ISSUE THREAD

**Issue by LiewFeng** [Cc-Hy/CMKD#18]
Hi, @Cc-Hy , could you kindly provide the config file of the teacher model? Lots of thanks!

**Comment by Cc-Hy** [comment]
Hi, @LiewFeng 
We have updated the config files and the teacher model configs can be found in each of the folder in .../CMKD-xx/.

**Comment by LiewFeng** [comment]
Thanks!

**Comment by LiewFeng** [comment]
Hi, @Cc-Hy , it seems that the teacher model is trained with both trainining and validation set. Is it reasonable?

**Comment by LiewFeng** [comment]
It' normal for test set, but kind of strange for validation set due to the inheriting of bev encoder and head from teacher model. Could you kindly provide the teacher model trained with only training set? Lots of thanks!

**Comment by Cc-Hy** [comment]
Hi, 
Due to the long time, many files have been cleaned up. I searched my device but did not find the checkpoint files.
I have been short of computing resources recently, and I may not be able to train the model recently. So you may use the config file [here](https://github.com/Cc-Hy/CMKD/blob/main/tools/cfgs/kitti_models/CMKD/CMKD-scd/second_teacher.yaml) to train a teacher model and change the training set, which does not take long.

**Comment by Cc-Hy** [comment]
I have also updated some other teacher models' config files (not very well tuned), and you may also use them if you are interested.

**Comment by LiewFeng** [comment]
Hi, @Cc-Hy , I try with the the config you mentioned but get th following two errors.
1. when getting dataloader. pcdet/datasets/__init__.py, line 85
`ValueError: sampler option is mutually exclusive with shuffle`

3. when calculating the qfl loss. pcdet/models/dense_heads/anchor_head_single_qfl.py, line 97
`pytorch/aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [12,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.`

**Comment by Cc-Hy** [comment]
@LiewFeng Hi, I have made some attempts to fix the issues. You may try again now.

**Comment by LiewFeng** [comment]
Hi, @Cc-Hy , thanks. It runs. By the way, how many GPU do you use to train teacher model?

**Comment by Cc-Hy** [comment]
@LiewFeng I remember I used 4 GPUs at that time.

**Comment by LiewFeng** [comment]
Get.

**Comment by LiewFeng** [comment]
Hi, @Cc-Hy , I train the second teacher with 2GPU with trainval set. After 32 epoch training, I get 0 AP, which is quit strange. The loss is ~0.4. Any suggestions? By the way, the info path in config seems wrong for test.

**Comment by LiewFeng** [comment]
Hi, @Cc-Hy , the automatic validation after training gets right performance, but I get 0 AP with test.py. It really confuses me.

**Comment by LiewFeng** [comment]
It's due to the 'shuffle' in pcdet/datasets/init.py, line 88.

**Comment by Cc-Hy** [comment]
@LiewFeng 
Hi, you may upload your log file when you test the model and I can take a look into it.

**Comment by LiewFeng** [comment]
Modifying 'shuffle' in pcdet/datasets/init.py, line 88， works for test.py.
From
`shuffle= (sampler is None) and shuffle,`
to
`shuffle= (sampler is None) and shuffle and training,`

**Comment by charmeleonz** [comment]
@Cc-Hy @LiewFeng Hi, following your discussions, I'd like to ask if the SECOND teacher is pre-trained on Trainval or Train to give the reported ablation results evaluated on Val set in the CMKD paper? And is the provided SECOND model pre-trained on Trainval?

**Comment by Cc-Hy** [comment]
Hi @charmeleonz 
The above discussion raised because earlier I upload the teacher model trained on kitti trainval set for both validation experiments and test experiments. And the results in the paper and the teacher models provided in the model zoo now are all trained with kitti train set.

**Comment by charmeleonz** [comment]
@Cc-Hy I see. Thanks.

**Comment by charmeleonz** [comment]
@Cc-Hy Hi, in the model zoo, I am confused by the rows of "kitti train". Did these models not use eigen data? - which in turn means these models are trained in a fully supervised way without the CMKD framework?

**Comment by xiaoxusanheyi** [comment]
> 你好，@Cc-Hy，训练后的自动验证获得了正确的性能，但我使用 test.py 得到了 0 AP。这真的让我很困惑。
你好，我有个问题想咨询一下，为啥我在训练完进行测试的时候出现如图所示的好多error问题呢？
![8~K$HJEJ~A%W~(VQJ ZG0$T](https://github.com/Cc-Hy/CMKD/assets/113592382/dd12c4a7-1932-49ee-b970-b9c6cc6d062c)
