### ISSUE TITLE
Not familiar PCDet, can you give more detail training scripts?

### ISSUE THREAD

**Issue by Senwang98** [Cc-Hy/CMKD#2]
@Cc-Hy 
Hi, I am not familiar PCDet, can you give one training script?
BHW, where is the KD code line in your repo? I want to check your code part of KD loss.
Thanks your work!

**Comment by Cc-Hy** [comment]
@Senwang98 
Hi, we have released some instructions and scripts for KITTI experiments.
Feel free to let us know if there are any issues or bugs.

**Comment by Senwang98** [comment]
@Cc-Hy 
Great, thanks

**Comment by Senwang98** [comment]
@Cc-Hy 
By the way, I found SCNet performs bad performance when uesd in MonoDisll
