### ISSUE TITLE
Generation of depth GT

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#20]
Hi, thanks for the great work. 

Just wondering how the dense depth GT used in the image branch is generated? According to CaDDN, it is obtained by projection from LiDAR followed by depth completion. Is depth completion actually performed?

**Comment by Cc-Hy** [comment]
Hello,
The dense depth maps we use are provided by the  official [CaDDN](https://github.com/TRAILab/CaDDN)/[OpenPCDet](https://github.com/open-mmlab/OpenPCDet). And according to CaDDN, the depth completion is performed.
However, there are also some methods to directly use the sparse depth maps for supervision. For example, you can use min pooling operation or [sparse average pooling](https://github.com/Cc-Hy/CMKD/blob/5082b5ad09fafbe961ff510f008dd6979e13c58a/pcdet/datasets/processor/data_processor_cmkd.py#L304) to obtain the depth supervision labels.
