### ISSUE TITLE
Use of customised amount of training data

### ISSUE THREAD

**Issue by carlvinson70** [Cc-Hy/CMKD#22]
Hi author, does the code support training with customised amounts of training data (to reproduce Figure 7's results in the paper)? If not, how do we go about this?

**Comment by Cc-Hy** [comment]
Hi,
A very direct way to do this is to customize a split file just like [this](https://github.com/Cc-Hy/CMKD/blob/main/data/kitti/ImageSets/kitti_train_and_eigen_clean.txt). You can put the chosen sample ids into it and generate a .pkl file and use it for training. 
Another way is to modify the [dataset.py file](https://github.com/Cc-Hy/CMKD/blob/main/pcdet/datasets/kitti/kitti_dataset_cmkd.py#L43), where you modify kitti_infos to adaptively choose training samples.
