### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'POST_PROCESSING'

### ISSUE THREAD

**Issue by xiaoxusanheyi** [Cc-Hy/CMKD#25]
AttributeError: 'EasyDict' object has no attribute 'POST_PROCESSING'
![image](https://user-images.githubusercontent.com/113592382/224518044-25bbf239-f3c8-491c-b32a-deae546a7504.png)

执行命令python train_cmkd.py --cfg /home/ubuntu/CMKD/tools/cfgs/kitti_models/CMKD/CMKD-scd/cmkd_kitti_eigen_R50_scd_bev.yaml，训练30个epoch出现上面那个错误，也就是你们建议的训练技巧，是怎么回事？

**Comment by Cc-Hy** [comment]
That's ok, don't care about it. After training it will automatically run inference and the xxx_bev.yaml config file is not complete so it will have a problem with inference. And when you complete detection training the error will disappear.

**Comment by xiaoxusanheyi** [comment]
> 

也就是说这条命令python train_cmkd.py --cfg /home/ubuntu/CMKD/tools/cfgs/kitti_models/CMKD/CMKD-scd/cmkd_kitti_eigen_R50_scd_bev.yaml是正确的，然后训练完去执行下一条命令python train_cmkd.py --cfg /tools/cfgs/kitti_models/CMKD/CMKD-scd/cmkd_kitti_eigen_R50_scd_V2.yaml --pretrained_img_model +上面命令训练完的第30个epoch   训练10个后测试吗？

**Comment by Cc-Hy** [comment]
Yes, after you run the second detection training command, this error will not occur.

**Comment by xiaoxusanheyi** [comment]
> 是的，你运行第二次检测训练命令后，就不会出现这个错误了。

1）最早的时候，我也是那样训练的，但是最后检测的出的结果，不管是汽车、行人还是自行车的bev、3d数据都是00，00，稍后我会在训练，测试一遍，看看是否数据是否正常。
2）在多GPU训练的命令中有加载的--pretrained_lidar_model checkpoints/second_teacher.pth，但为什么在We recommand to use the following training skill (BEV first, then whole model)命令训练方式中就没有了呢？ 上述1）的问题是不是也是此原因呢？

**Comment by Cc-Hy** [comment]
In 'We recommand to use the following training skill' part, the commands are simplified to explain the training skill.
And you should complete the commands with the rest arguments.

For all 0 results, you may upload the log file and I can look into it to find the potential problems.

**Comment by xiaoxusanheyi** [comment]
你好，作者：
          感谢你精彩的工作，我几个问题想咨询一下：  
        你们GitHub更新的数据结果是通过多GPU训练bev+测试V2直接得出来的最后结果吗？如果不是的话，请问是怎么得出这个结果呢？
        论文中的下面这张图：这个结果是直接（训练30+训练10+测试10）跑出来的结果吗？期待你的回信谢谢烟大徐龙
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/18/2023 11:17
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [Cc-Hy/CMKD] AttributeError: 'EasyDict' object has no attribute 'POST_PROCESSING' (Issue #25)
        
      
    
  

In 'We recommand to use the following training skill' part, the commands are simplified to explain the training skill.
And you should complete the commands with the rest arguments.
For all 0 results, you may upload the log file and I can look into it to find the potential problems.

**Comment by TimGor1997** [comment]
> > 是的，你运行第二次检测训练命令后，就不会出现这个错误了。
> 
> 1）最早的时候，我也是那样训练的，但是最后检测的出的结果，不管是汽车、行人还是自行车的bev、3d数据都是00，00，稍后我会在训练，测试一遍，看看是否数据是否正常。 2）在多GPU训练的命令中有加载的--pretrained_lidar_model checkpoints/second_teacher.pth，但为什么在We recommand to use the following training skill (BEV first, then whole model)命令训练方式中就没有了呢？ 上述1）的问题是不是也是此原因呢？

大佬您好！我想问一下，最终00，00的问题解决了吗？请问是什么原因造成的呢？
