### ISSUE TITLE
Why training script automatic evaluate the last 10 epoch?

### ISSUE THREAD

**Issue by Senwang98** [Cc-Hy/CMKD#27]
@Cc-Hy 
Hi, 
I try to train `kitti train`, I change epoch10 to epoch20. But the training always eval the last 10 checkpoint.
How can I eval 1~10 checkpoint?
![image](https://user-images.githubusercontent.com/23122139/227089943-735d827f-e0bb-4b6b-8fd9-15dfdf6728cd.png)

**Comment by Cc-Hy** [comment]
Hi, you can change the command [here](https://github.com/Cc-Hy/CMKD/blob/main/tools/train_cmkd.py#L207) to set the number.

**Comment by Senwang98** [comment]
@Cc-Hy 
Thanks for your reply
