### ISSUE TITLE
nuScenes dataset evaluation

### ISSUE THREAD

**Issue by BatuhanYilmaz** [Cc-Hy/CMKD#28]
Hi, thanks for your great work!

I'm trying to get results from nuScenes mini dataset.
Do you plan to add a brief documentation about this dataset?

Cheers,

Batuhan

**Comment by Cc-Hy** [comment]
Hi, thanks for your attetion. We have released the implementation for Nuscenes dataset, you may explore it. And we will update more instructions later.

**Comment by BatuhanYilmaz** [comment]
Thank you for the fast reply, I'll check that implementation.
