### ISSUE TITLE
Can release code for train teacher model?

### ISSUE THREAD

**Issue by xiaowenhe** [Cc-Hy/CMKD#3]
Hi, Can release code for train teacher model? Thank you !

**Comment by Cc-Hy** [comment]
Hi, this repo is compatible with OpenPCDet,
so you can follow the [official instruction](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md) to train any LiDAR-based teacher model.

To train the teacher model in the paper, use
`
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg cfgs/kitti_models/second_teacher.yaml
`
