### ISSUE TITLE
Extremely low eval results

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#34]
Hi,

I recently started running the code on a new machine. Strangely the eval AP results become extremely bad (see the screenshot). Yet, the other results (i.e. recall, precision, avg no. of objects) look ok (I think?). What might be the cause? Thanks.

![Screenshot from 2023-04-09 20-05-17](https://user-images.githubusercontent.com/125424140/230772097-1af17f64-6ab2-44b2-9e69-24ed7e2619b1.png)
![Screenshot from 2023-04-09 20-05-25](https://user-images.githubusercontent.com/125424140/230772098-ddfd57eb-77d6-4181-ab31-6478dbe35878.png)

**Comment by Cc-Hy** [comment]
Hi, @charmeleonz
You may take a look at [this solution](https://github.com/Cc-Hy/CMKD/issues/18#issuecomment-1436191699) to see whether it works.
