### ISSUE TITLE
Huge fluctuations in eval results with test.py 

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#35]
Hi, I ran into some very strange results. I pre-trained a SECOND teacher for 80 epochs. 

When evaluating the 60th and 80th epochs' checkpoints with test.py, the results are good (Car-Mod>80), but the 70th epoch gives extremely bad results (Car-Mod~10, average predicted number of objects: 300+).

I also followed the advice in another issue to modify __init__.py under pcdet/datasets/ but it didn't help.

The SECOND model is trained on Train and evaluated on Val.

![Screenshot from 2023-04-15 09-39-37](https://user-images.githubusercontent.com/125424140/232177046-aedcedda-b4f0-4f85-990c-6d1183c6698c.png)

**Comment by Cc-Hy** [comment]
Hi, how are the losses going at the abnormal epoch? And how is the performance just before or after this epoch (i.e., 69 and 71)? Maybe you can check these out for some leads.
