### ISSUE TITLE
响应蒸馏那部分的分类蒸馏的loss具体在源码那个位置？

### ISSUE THREAD

**Issue by xiaoxusanheyi** [Cc-Hy/CMKD#37]
你好，作者：看了源码不知道这个分类loss的源码的具体位置在哪里：希望作者给指出loss具体位置。
![image](https://user-images.githubusercontent.com/113592382/233758272-462b140b-5c63-4905-999c-62000760260b.png)

**Comment by Cc-Hy** [comment]
This loss is implemented in [this line for anchor head](https://github.com/Cc-Hy/CMKD/blob/cfc4492bd57e6c485a09f5a14bcbc6b03e8d5ab5/pcdet/models/dense_heads/anchor_head_single_cmkd_v2.py#L97) and [this line for center head](https://github.com/Cc-Hy/CMKD/blob/cfc4492bd57e6c485a09f5a14bcbc6b03e8d5ab5/pcdet/models/dense_heads/center_head_soft.py#L242). Note that si is removed in the classification loss in current version.

**Comment by xiaoxusanheyi** [comment]
> 收到，感谢
还有个问题就是，我看到这两个文件cmkd_kitti_eigen_R50_scd_bev.yaml和cmkd_kitti_eigen_R50_scd_V2.yaml中的info-path的'train'都是 [kitti_infos_kitti_train_and_eigen_clean.pkl]，而数据集配置文件kitti_dataset.yaml的INFO_PATH:是'train': [kitti_infos_train.pkl], 我要进行kitti_raw数据集训练验证测试，是否需要将kitti_dataset.yaml的INFO_PATH的'train': 的[kitti_infos_train.pkl]改为kitti_infos_kitti_train_and_eigen_clean.pkl呢？  yes or no呀

**Comment by Cc-Hy** [comment]
The answer is no. 'kitti_infos_kitti_train_and_eigen_clean.pkl' contains data information of the eigen clean split and kitti train split, both of which are subsets of kitti raw. If you want to use the entire kitti raw, use the kitti raw split file to generate a new pkl file for training. Again, please refer to the datasets part in the paper to know about kitti train，kitti val，kitti trainval，kitti test，eigen clean and kitti raw, they are different.

**Comment by xiaoxusanheyi** [comment]
不好意思作者，我也是第一次使用这个kitti_raw，对于你这句话“ If you want to use the entire kitti raw, use the kitti raw split file to generate a new pkl file for training. ”不理解，我也是很着急使用，希望作者告知如何去生成这个新的pkl文件，谢谢。

**Comment by xiaoxusanheyi** [comment]
> 如果要使用整个kitti raw，使用kitti raw分割文件生成新的pkl文件进行训练。

作者，你看生成的不正确吗，
![image](https://user-images.githubusercontent.com/113592382/234162374-a66ce642-2cdb-4534-ac7c-2bcf8d4fced8.png)

**Comment by Cc-Hy** [comment]
The data split file [here](https://github.com/Cc-Hy/CMKD/blob/main/data/kitti/ImageSets/kitti_raw.txt) indicates the data samples for kitti raw. Change [this line](https://github.com/Cc-Hy/CMKD/blob/main/pcdet/datasets/kitti/kitti_dataset_cmkd.py#L590) to
`split_name = 'kitti_raw'`
and then run
`python -m pcdet.datasets.kitti.kitti_dataset_cmkd create_kitti_infos_unlabel tools/cfgs/dataset_configs/kitti_dataset.yaml`. This will generate the pkl file for kitti raw.

**Comment by xiaoxusanheyi** [comment]
> python -m pcdet.datasets.kitti.kitti_dataset_cmkd create_kitti_infos_unlabel tools/cfgs/dataset_configs/kitti_dataset.yaml

谢谢作者！

**Comment by xiaoxusanheyi** [comment]
> This loss is implemented in [this line for anchor head](https://github.com/Cc-Hy/CMKD/blob/cfc4492bd57e6c485a09f5a14bcbc6b03e8d5ab5/pcdet/models/dense_heads/anchor_head_single_cmkd_v2.py#L97) and [this line for center head](https://github.com/Cc-Hy/CMKD/blob/cfc4492bd57e6c485a09f5a14bcbc6b03e8d5ab5/pcdet/models/dense_heads/center_head_soft.py#L242). Note that si is removed in the classification loss in current version.

![image](https://github.com/Cc-Hy/CMKD/assets/113592382/3755659c-f845-4498-89ff-c0704b35dbb5)
zuo'zh作者你好，你看这不代码里的分类和回归有这个si呀，为啥说分类中没有这个si呀，回归中也没有吗？

**Comment by xiaoxusanheyi** [comment]
> 啥说分类中没有这个si呀，回

还有就是说 这个响应蒸馏中咋用的GT呀，
