### ISSUE TITLE
Models and results in Model Zoo

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#38]
Dear author, in the model zoo, I am confused by descriptions in the model zoo. Specifically, for models in rows of "kitti train", did they not use eigen data? - which in turn means these models are trained in a fully supervised way without the CMKD framework?

**Comment by Cc-Hy** [comment]
Hi, the models in the model zoo are all trained with the CMKD framework. For the kitti train samples, we just treat them as unlabeled.

**Comment by charmeleonz** [comment]
That makes sense, thanks!

**Comment by charmeleonz** [comment]
@Cc-Hy Hi, I'm curious why the KITTI val results by the 'kitti train' (that is, without eigen clean data) are even inferior to CaDDN's original val results? This seems to mean distillation and whatever LiDAR-induced knowledge even hurt CaDDN's performance. Could you kindly share your insights into this?

**Comment by xiaoxusanheyi** [comment]
> @Cc-Hy嗨，我很好奇为什么“kitti train”（即没有本征清洁数据）的 KITTI val 结果甚至不如 CaDDN 的原始 val 结果？这似乎意味着蒸馏和任何 LiDAR 诱导的知识甚至会损害 CaDDN 的性能。您能否分享您对此的见解？

你好，这个CMKD的model zoo 中kitti train”（即没有本征清洁数据）second那个数据是验证集上的3DAP吗？

**Comment by charmeleonz** [comment]
> > @Cc-Hy嗨，我很好奇为什么“kitti train”（即没有本征清洁数据）的 KITTI val 结果甚至不如 CaDDN 的原始 val 结果？这似乎意味着蒸馏和任何 LiDAR 诱导的知识甚至会损害 CaDDN 的性能。您能否分享您对此的见解？
> 
> 你好，这个CMKD的model zoo 中kitti train”（即没有本征清洁数据）second那个数据是验证集上的3DAP吗？

Yes I believe so.

**Comment by xiaoxusanheyi** [comment]
> > > @Cc-Hy嗨，我很好奇为什么“kitti train”（即没有本征清洁数据）的 KITTI val 结果甚至不如 CaDDN 的原始 val 结果？这似乎意味着蒸馏和任何 LiDAR 诱导的知识甚至会损害 CaDDN 的性能。您能否分享您对此的见解？
> > 
> > 
> > 你好，这个CMKD的model zoo 中kitti train“（即没有本征清洁数据）second那个数据是验证集上的3DAP吗？
> 
> 是的，我相信是的。

感谢！还有一个问题就是说CMKD 该如何可视化呢 就想原文图8的可视化图片那样，该使用那条指令呢？
