### ISSUE TITLE
Inconsistent evaluation results

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#41]
Hi, 

I ran into inconsistent evaluation results where the automatic eval at the end of training and manual evaluation using test.py give slight different results for the same checkpoint. Sometimes the AP differs by ~1 AP and sometimes < 1 AP. Do you have any idea why?

What I am training and evaluating is a CaDDN model using the provided CaDDN.yaml.

**Comment by Cc-Hy** [comment]
I've been in some similar situations, but the gap is not as large as yours.
Maybe it has something to do with the dataloader and I have made some modification to the dataloader, please try again to see whether this issue still exits.
