### ISSUE TITLE
Questions about teacher models

### ISSUE THREAD

**Issue by RookieHuang** [Cc-Hy/CMKD#45]
Anyone have an idea about why CenterPoint and PointPillar are the worse teacher models than SECOND, even if they perform better than SECOND?

**Comment by Cc-Hy** [comment]
Hi,
Sorry for being late. According to our earlier experiments, a better teacher model will not necessarily lead to better student results. And similar conclusions have been reached in other papers. I think it's more important to make it more suitable for students to learn from the teacher models than to make the teacher models themselves better.
For example, I have attempted to use some two-stage teachers, which are much better in performance. However, the results are not better. In many cases, the improvement in the performance of the lidar model comes from its deeper extraction of point cloud information, which may be difficult for the student model to learn. 
Hope the above can help you a little.

**Comment by RookieHuang** [comment]
Thank for your reply!
