### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by TJRadarLab** [Cc-Hy/CMKD#48]
Sorry to disturb you, I would like to ask you a few questions:
    During the calculation of MSE loss for the supervised middle layer BEV features, there are many empty values. How did you consider this? Did you add a mask to the 0 values?
    When I trained with other data, I found that the overall loss is affected by the BEV layer. The loss of the later anchors is very low, and the recall rate of the test results is very poor. Have you encountered this problem?
    Thank you, looking forward to your reply~

**Comment by Cc-Hy** [comment]
Hi, 
A straightforward method is to add a none-zero mask to the BEV loss. I remember trying it once, but the results seem to be similar. You can try it to see the effect.
As for the results on other data, have you checked the teacher model's performance, if yes, is it reasonable? And can you please describe the meaning of 'later anchors', and I can offer some helps.
