### ISSUE TITLE
kitti_3D的CMKD可视化问题

### ISSUE THREAD

**Issue by youtodohaveyou** [Cc-Hy/CMKD#49]
你好，作者：
     使用KITTI-3D数据集的CMKD框架该如何实现图片8的可视化呢，希望作者给出详细的细节。
感谢！

**Comment by Cc-Hy** [comment]
Hi, if your machine has GUI, you may first try add --vis_online after test_cmkd.py in the command line to see if it works.

**Comment by youtodohaveyou** [comment]
作者你好，我们服务器有桌面的可视化环境，我总结一下就是说：训练完去测试的话执行，把这个参数  --vis_online 加到github的那条测试命令即可是吗？ 我给出的多GPU训练命令如下 ，直接执行即可吗？   
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 test_cmkd.py ----vis_online --launcher pytorch --cfg ${CONFIG_FILE} --tcp_port 16677 --ckpt ${CKPT}

**Comment by youtodohaveyou** [comment]
你好，作者，我训练完继进行测试生成的可视化图片，为啥看着很怪呢？
![image](https://github.com/Cc-Hy/CMKD/assets/142576676/eeed6403-d4bf-43ad-aa40-8f75320a67dc)

**Comment by youtodohaveyou** [comment]
就是说感觉检测的图片不是原本这张图片的可视化呀，这是咋回事呢？
![image](https://github.com/Cc-Hy/CMKD/assets/142576676/30489e53-cb71-4cd0-8fa5-2c3719a9e228)
