### ISSUE TITLE
How to download the calib files of kitty_raw

### ISSUE THREAD

**Issue by WoodwindHu** [Cc-Hy/CMKD#5]
When I try to generate the data infos of kitty_cmkd, it raised an error that data/kitti/raw/calib/2011_09_30.txt is missed. 
However, the kitty raw data downloaded with the [raw dataset download script](https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data_downloader.zip) only provide the three calib files: calib_cam_to_cam.txt, calib_imu_to_velo.txt, and calib_velo_to_cam.txt.
So how to download the calib files of kitty_raw?

**Comment by Cc-Hy** [comment]
Hi, I have uploaded the processed calib files, you can find them [here](https://github.com/Cc-Hy/CMKD/tree/main/data/kitti/raw/calib).

**Comment by WoodwindHu** [comment]
Thank you very much for your kindly help!
