### ISSUE TITLE
what is the performance on kitti train

### ISSUE THREAD

**Issue by LiewFeng** [Cc-Hy/CMKD#8]
Hi, @Cc-Hy , I wonder the performance on the kitti train. Can you kindly provide it? Lots of thanks!

**Comment by Cc-Hy** [comment]
@LiewFeng Here are two typical results trained with KITTI train only.

![image](https://user-images.githubusercontent.com/82150240/208624928-7a57951a-d27c-4cab-b621-d4f4e7dad7c2.png) ![image](https://user-images.githubusercontent.com/82150240/208626039-b92ff9b1-9958-47c7-9c84-278e1a5841bb.png)

And you can also refer to our paper for more results.

**Comment by LiewFeng** [comment]
Thank you very much for your quick reply!
I run the code for 2 times and get a slightly different results from the paper. And as you mentioned in the README, this implementation has some differences from your paper. That's the reason I wonder the performance on the kitti train.
![image](https://user-images.githubusercontent.com/42316773/208661711-9cb27da7-f871-4686-9be7-0a1ea5f60b0c.png)
![image](https://user-images.githubusercontent.com/42316773/208661768-14605fb8-d42c-45b4-b124-54d6d1f31dd5.png)
The performance on hard is about 1 point lower than taht on the paper and the performance on easy is 1 point higher than that on the paper but not very stable. The results is obtained with 1 GPU. I will try 2 GPUs latter. By the way, does it affect performance much?

**Comment by Cc-Hy** [comment]
@LiewFeng 
Hi, I believe it is a common seen situation that the results trained with KITTI train is unstable.
For one thing, the number of KITTI train samples is small and the performance often varies 1-2 point or more, and this happens a lot when I'm training my code or using someone else's repo.
For another, different softwares and hardwares may also cause a difference.

So if you can not exactly reproduce our results, just set your own results as the baseline and do the experiments.
Also, BEV based/dense depth based methods need more training samples to be powerful and stable, you may use the unlabeled samples for a try.

**Comment by LiewFeng** [comment]
Thanks. I will try the unlabeled smaples latter. The downloading of raw data really takes time.

**Comment by Cc-Hy** [comment]
@LiewFeng 
I think so, too. And the data of Waymo and Nuscenes is even bigger, so take your time.

**Comment by LiewFeng** [comment]
Okay. Looking forward to your code on these two datasets.
